### ISSUE TITLE
tests don't call relibc implementation of string functions.

### ISSUE THREAD

**Issue by jrraymond** [redox-os/relibc#67]
I was implementing `strpbrk`, which calls `strcspn`. When called from inside my implementation of `strpbrk`, `strcspn` was crashing at `src/string/src/lib.rs:140: attempt to shift left with overflow` on the inputs `hello, worlde`, `aeiouy`.  However, when I called `strcspn` from the tests with the same inputs it worked.

So I commented out almost the entire implementaiton of `strcspn` so it would always return `0`. But when I run the tests `strcspn` still produces the correct results.

I also commented out most of the implementation of `strspn` and `strchr`, and they still produce the correct results. So I added back the `uniplemented!` macro and the tests still work.

I wonder if this is just some quirk of my system?

**Comment by jrraymond** [comment]
but the tests are calling the implementation of `strpbrk`, because otherwise I wouldn't see that crash from `lib.rs`. So some of the functions are getting called and some are not.

**Comment by Tommoa** [comment]
Ok, I'm somewhat getting the same thing you are. I tried returning 0 from `strcspn` and it just gave me the expected results.

With regards to the error that you're getting, you're correct, turns out I misread the macro that I was trying to expand from musl. It should be `8*byteset.len()` instead of `8*mem::size_of ...`. I'll send through a PR soonish.

**Comment by azymohliad** [comment]
@jrraymond I'm sorry that I also implemented srtpbrk() and made a pull request. I didn't see this issue when I started, so I didn't know you are also doing it.
